/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class kalkulator1 extends javax.swing.JFrame {
    String angka="";
        double jumlah,angka1, angka2;
        int pilih;
    /**
     * Creates new form kalkulator1
     */
    public kalkulator1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        hasil = new javax.swing.JTextField();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        button0 = new javax.swing.JButton();
        penjumlahan = new javax.swing.JButton();
        pengurangan = new javax.swing.JButton();
        perkalian = new javax.swing.JButton();
        samadengan = new javax.swing.JButton();
        pembagian = new javax.swing.JButton();
        buttonkoma = new javax.swing.JButton();
        persen = new javax.swing.JButton();
        akar = new javax.swing.JButton();
        pangkat = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        modulus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        jLabel1.setText("  Kalkulator");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 10, 180, 29);

        clear.setBackground(new java.awt.Color(102, 255, 102));
        clear.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        clear.setText("C");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear);
        clear.setBounds(10, 120, 120, 40);

        hasil.setBackground(new java.awt.Color(255, 255, 102));
        jPanel1.add(hasil);
        hasil.setBounds(10, 50, 230, 60);

        button1.setText("1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1);
        button1.setBounds(10, 170, 40, 40);

        button2.setText("2");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel1.add(button2);
        button2.setBounds(70, 170, 40, 40);

        button3.setText("3");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        jPanel1.add(button3);
        button3.setBounds(140, 170, 40, 40);

        button4.setText("4");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        jPanel1.add(button4);
        button4.setBounds(200, 170, 40, 40);

        button5.setText("5");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        jPanel1.add(button5);
        button5.setBounds(10, 220, 40, 40);

        button6.setText("6");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        jPanel1.add(button6);
        button6.setBounds(70, 220, 40, 40);

        button7.setText("7");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        jPanel1.add(button7);
        button7.setBounds(140, 220, 40, 40);

        button8.setText("8");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        jPanel1.add(button8);
        button8.setBounds(200, 220, 40, 40);

        button9.setText("9");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        jPanel1.add(button9);
        button9.setBounds(30, 270, 40, 40);

        button0.setText("0");
        button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button0ActionPerformed(evt);
            }
        });
        jPanel1.add(button0);
        button0.setBounds(180, 270, 40, 40);

        penjumlahan.setBackground(new java.awt.Color(153, 255, 255));
        penjumlahan.setText("+");
        penjumlahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjumlahanActionPerformed(evt);
            }
        });
        jPanel1.add(penjumlahan);
        penjumlahan.setBounds(10, 340, 40, 30);

        pengurangan.setBackground(new java.awt.Color(153, 255, 255));
        pengurangan.setText("-");
        pengurangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penguranganActionPerformed(evt);
            }
        });
        jPanel1.add(pengurangan);
        pengurangan.setBounds(70, 340, 40, 30);

        perkalian.setBackground(new java.awt.Color(153, 255, 255));
        perkalian.setText("X");
        perkalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perkalianActionPerformed(evt);
            }
        });
        jPanel1.add(perkalian);
        perkalian.setBounds(200, 340, 40, 30);

        samadengan.setBackground(new java.awt.Color(153, 153, 255));
        samadengan.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        samadengan.setText("=");
        samadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samadenganActionPerformed(evt);
            }
        });
        jPanel1.add(samadengan);
        samadengan.setBounds(40, 380, 170, 25);

        pembagian.setBackground(new java.awt.Color(153, 255, 255));
        pembagian.setText("/");
        pembagian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembagianActionPerformed(evt);
            }
        });
        jPanel1.add(pembagian);
        pembagian.setBounds(140, 340, 40, 30);

        buttonkoma.setBackground(new java.awt.Color(204, 255, 204));
        buttonkoma.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        buttonkoma.setText(".");
        buttonkoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonkomaActionPerformed(evt);
            }
        });
        jPanel1.add(buttonkoma);
        buttonkoma.setBounds(190, 120, 50, 40);

        persen.setBackground(new java.awt.Color(153, 255, 255));
        persen.setText("%");
        persen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persenActionPerformed(evt);
            }
        });
        jPanel1.add(persen);
        persen.setBounds(80, 300, 43, 30);

        akar.setBackground(new java.awt.Color(153, 255, 255));
        akar.setText("√");
        akar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akarActionPerformed(evt);
            }
        });
        jPanel1.add(akar);
        akar.setBounds(130, 300, 40, 30);

        pangkat.setBackground(new java.awt.Color(153, 255, 255));
        pangkat.setText("X^Y");
        pangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pangkatActionPerformed(evt);
            }
        });
        jPanel1.add(pangkat);
        pangkat.setBounds(90, 270, 73, 23);

        keluar.setBackground(new java.awt.Color(102, 102, 102));
        keluar.setText(">");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel1.add(keluar);
        keluar.setBounds(230, 0, 20, 20);

        modulus.setBackground(new java.awt.Color(204, 255, 204));
        modulus.setText("M");
        modulus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulusActionPerformed(evt);
            }
        });
        jPanel1.add(modulus);
        modulus.setBounds(140, 130, 40, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        angka += "3";
        hasil.setText(angka);
    }//GEN-LAST:event_button3ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
        angka += "6";
        hasil.setText(angka);
    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        // TODO add your handling code here:
        angka += "7";
        hasil.setText(angka);
    }//GEN-LAST:event_button7ActionPerformed

    private void button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button0ActionPerformed
        // TODO add your handling code here:
        angka += "0";
        hasil.setText(angka);
    }//GEN-LAST:event_button0ActionPerformed

    private void penjumlahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjumlahanActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        hasil.setText("+");
        angka = "";
        pilih = 1;
    }//GEN-LAST:event_penjumlahanActionPerformed

    private void perkalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perkalianActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        hasil.setText("*");
        angka ="";
        pilih = 4;
    }//GEN-LAST:event_perkalianActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        angka += "1";
        hasil.setText(angka);
    }//GEN-LAST:event_button1ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
       hasil.setText(angka);
       angka1 = 0.0;
       angka2 = 0.0;
       jumlah = 0.0;
       angka = "";
    }//GEN-LAST:event_clearActionPerformed

    private void buttonkomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonkomaActionPerformed
        // TODO add your handling code here:
        angka += ".";
        hasil.setText(angka);
    }//GEN-LAST:event_buttonkomaActionPerformed

    private void penguranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penguranganActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        hasil.setText("-");
        angka ="";
        pilih = 2;
    }//GEN-LAST:event_penguranganActionPerformed

    private void pembagianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembagianActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        hasil.setText(angka);
        angka = "";
        pilih = 3;
    }//GEN-LAST:event_pembagianActionPerformed

    private void samadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samadenganActionPerformed
        // TODO add your handling code here:
        switch(pilih){
            case 1:
                angka2 = Double.parseDouble(angka);
                jumlah = angka1 + angka2;
                angka = Double.toString(jumlah);
                hasil.setText(angka);
                break;
            case 2:
                angka2 = Double.parseDouble(angka);
                jumlah = angka1 - angka2;
                angka = Double.toString(jumlah);
                hasil.setText(angka);
                break;
            case 3:
                angka2 = Double.parseDouble(angka);
                jumlah = angka1 / angka2;
                angka = Double.toString(jumlah);
                hasil.setText(angka);
                break;
            case 4:
                angka2 = Double.parseDouble(angka);
                jumlah = angka1 * angka2;
                angka = Double.toString(jumlah);
                hasil.setText(angka);
                break;
            case 5:
                angka2 = Double.parseDouble(angka);
                jumlah = angka1 % angka2;
                angka = Double.toString(jumlah);
                hasil.setText(angka);
                break;
            case 6:
                jumlah = Math.sqrt(angka1);
                angka = Double.toString(jumlah);
                hasil.setText(angka);
                break;
            case 7:
                angka2 = Double.parseDouble(angka);
                jumlah = Math.pow(angka1, angka2);
                angka = Double.toString(jumlah);
                hasil.setText(angka);
                break;
            case 8:
                jumlah = angka1 / 100;
                angka = Double.toString(jumlah);
                hasil.setText(angka);
                break;
                default:
                break;
        }
    }//GEN-LAST:event_samadenganActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        angka += "2";
        hasil.setText(angka);
    }//GEN-LAST:event_button2ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
        angka += "4";
        hasil.setText(angka);
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
        angka += "5";
        hasil.setText(angka);
    }//GEN-LAST:event_button5ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        // TODO add your handling code here:
        angka += "8";
        hasil.setText(angka);
    }//GEN-LAST:event_button8ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        // TODO add your handling code here:
        angka += "9";
        hasil.setText(angka);
    }//GEN-LAST:event_button9ActionPerformed

    private void persenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persenActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        hasil.setText(angka);
        angka = "";
        pilih = 8;
    }//GEN-LAST:event_persenActionPerformed

    private void akarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akarActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        hasil.setText(angka);
        angka = "";
        pilih = 6;
    }//GEN-LAST:event_akarActionPerformed

    private void pangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pangkatActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        hasil.setText(angka);
        angka = "";
        pilih = 7;
    }//GEN-LAST:event_pangkatActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_keluarActionPerformed

    private void modulusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulusActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        hasil.setText(angka);
        angka = "";
        pilih = 5;
    }//GEN-LAST:event_modulusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kalkulator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kalkulator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kalkulator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kalkulator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kalkulator1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton akar;
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton buttonkoma;
    private javax.swing.JButton clear;
    private javax.swing.JTextField hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton modulus;
    private javax.swing.JButton pangkat;
    private javax.swing.JButton pembagian;
    private javax.swing.JButton pengurangan;
    private javax.swing.JButton penjumlahan;
    private javax.swing.JButton perkalian;
    private javax.swing.JButton persen;
    private javax.swing.JButton samadengan;
    // End of variables declaration//GEN-END:variables
}
